opt_out_usage

# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  lane :deploy do
    setup_travis
    clean_build_artifacts
    ensure_git_status_clean

    build_number = Time.new.utc.strftime("%y%m%d.%H%M")
    log = "[Install directly to iOS device here!](https://hontheim.net/deploy/ulp/)\n\nChangelog:\n\n" + changelog_from_git_commits(
      pretty: "- %s",
      date_format: "short",
      merge_commit_filtering: "exclude_merges",
      match_lightweight_tag: true
    )

    increment_build_number(
      build_number: build_number
    )
    commit_version_bump
    new_tag = "v" + get_version_number(target: "UrbanLifePlusApp") + "\-" + get_build_number
    add_git_tag(
      tag: "ci/" + new_tag
    )

    # push_to_git_remote(
    #   remote: "origin",
    #   local_branch: "HEAD",
    #   remote_branch: ENV["TRAVIS_BRANCH"],
    #   tags: true
    # )
    sh("git remote add travis git@github.com:hhontheim/UrbanLifePlusApp.git")
    sh("git push travis master --tags")

    match(type: "development", readonly: is_ci)
    match(type: "adhoc", readonly: is_ci)

    # run_tests

    # sh("brew install imagemagick")

    # snapshot
    # frameit(
    #  path: "./build/screenshots"
    # )
    # zip(
    #  path: "./build/screenshots",
    #  output_path: "./build/screenshots.zip"
    # )

    gym(export_options: {
      method: "ad-hoc",
      include_bitcode: false,
      include_symbols: false,
      manifest: {
        appURL: "url_to_replace",
        displayImageURL: "https://hontheim.net/deploy/ulp/57.png",
        fullSizeImageURL: "https://hontheim.net/deploy/ulp/512.png"
      }
    })

    sh("sh ./upload_sftp.sh " + new_tag)

    github_release = set_github_release(
      repository_name: "hhontheim/UrbanLifePlusApp",
      api_token: ENV["GITHUB_TOKEN"],
      name: new_tag,
      tag_name: "ci/" + new_tag,
      description: log,
      commitish: "master",
      is_prerelease: false,
      upload_assets: ["./build/app.ipa"] # , "./build/screenshots.zip"]
    )
  end

  lane :register do
    register_devices(devices_file: "./devices.txt")
    match(type: "adhoc", force_for_new_devices: true)
    match(type: "development", force_for_new_devices: true)
  end

end
